# Generated by Django 5.2.5 on 2025-08-16 15:42

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usermodel',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nickname'),
        ),
    ]
